# Generated by Django 2.1.2 on 2018-10-24 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class1',
            fields=[
                ('borderid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('typeid', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('sum', models.IntegerField()),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('class1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Class1')),
            ],
        ),
        migrations.CreateModel(
            name='Electrical',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('sum', models.IntegerField()),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('class1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Class1')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('sum', models.IntegerField()),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('class1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Class1')),
            ],
        ),
        migrations.CreateModel(
            name='Ingre',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('addr', models.CharField(max_length=30)),
                ('boss', models.CharField(max_length=30)),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('name_id', models.CharField(max_length=30)),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('in_time', models.DateField()),
                ('no_time', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='ingre',
            field=models.ManyToManyField(to='goods.Ingre'),
        ),
        migrations.AddField(
            model_name='food',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Production'),
        ),
        migrations.AddField(
            model_name='food',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Warehouse'),
        ),
        migrations.AddField(
            model_name='electrical',
            name='ingre',
            field=models.ManyToManyField(to='goods.Ingre'),
        ),
        migrations.AddField(
            model_name='electrical',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Production'),
        ),
        migrations.AddField(
            model_name='electrical',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Warehouse'),
        ),
        migrations.AddField(
            model_name='drink',
            name='ingre',
            field=models.ManyToManyField(to='goods.Ingre'),
        ),
        migrations.AddField(
            model_name='drink',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Production'),
        ),
        migrations.AddField(
            model_name='drink',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Warehouse'),
        ),
    ]
